# -*- coding: utf-8 -*-
"""consumer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oOT4bvv-veWPqP_3wblUSqdaNBsYNn6
"""

!pip install kafka-python==1.4.7 --force-reinstall

from kafka import KafkaConsumer
import json

# Kafka consumer
consumer = KafkaConsumer(
    'demo_testing2',  # Topic name
    bootstrap_servers='public_ip:9092',  # Kafka broker (EC2 public IP)
    auto_offset_reset='earliest',
    enable_auto_commit=True,
    value_deserializer=lambda v: v.decode('utf-8')  # Decode as plain text first
)

print("Listening for messages on topic 'demo_testing2'...")

for message in consumer:
    try:
        _ = json.loads(message.value)  # Consume and parse JSON
        # No printing or processing, just consuming
    except json.JSONDecodeError:
        # Just consume non-JSON messages silently
        pass

