# -*- coding: utf-8 -*-
"""producer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bD1yEQjGG3OiLAC2e8-6w0j3iqp9cYgv
"""

# Clean old versions
!pip uninstall -y kafka-python kafka

# Install the working version
!pip install kafka-python==1.4.7

from kafka import KafkaProducer
import json
import time
import random
from datetime import datetime

# Kafka producer configuration
producer = KafkaProducer(
    bootstrap_servers='public_ip:9092',
    value_serializer=lambda v: json.dumps(v).encode('utf-8'),
    linger_ms=5,
    batch_size=32768,
    compression_type='gzip'
)

print("KafkaProducer initialized successfully!")

topic = "demo_testing2"

try:
    while True:
        messages_to_send = random.randint(100, 200)
        for _ in range(messages_to_send):
            data = {
                "sensor_id": random.randint(1, 100),
                "temperature": round(random.uniform(15.0, 45.0), 2),
                "status": random.choice(["ok", "warn", "fail"]),
                "timestamp": datetime.now().isoformat()
            }
            producer.send(topic, value=data)

        producer.flush()
        print(f"Sent {messages_to_send} messages")

        # Tight loop with minimal delay
        time.sleep(1)
except KeyboardInterrupt:
    print("Producer stopped by user.")
finally:
    producer.flush()
    producer.close()

